import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='navbar bg-base-100'>
          <div className='flex-1'>
            <Link href='/' className='btn btn-ghost normal-case text-xl'>
              Greg's portfolio
            </Link>
          </div>
          <div className='flex-none'>
            <ul className='menu menu-horizontal px-1'>
              <li>
                <Link href='/about'>About</Link>
              </li>
              <li>
                <Link href='/about/contact'>Contact</Link>
              </li>
              <li>
                <Link href='/githubusers'>Github Users</Link>
              </li>
            </ul>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
